title: JKxz
author: XUJINKAI
description: åŠªåŠ›å†™ç‚¹å„¿æœ‰ç”¨çš„â¤ï¸
footer_desc: >-
  <br>
  Â© 2016-2023 XUJINKAI.NET <br>
  Powered by <a href="https://github.com/XUJINKAI/blog">XUJINKAI blog</a>

url: https://xujinkai.net
baseurl: 
disqus: xujinkai
ga4: G-4Q0MVTQ7HL

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      comments: true
      toc: true
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
      comments: false

show_excerpts: true
locale: zh-Hans
lang: zh-Hans
date_format: "%Y-%m-%d"
timezone: Asia/Shanghai
# timezone: Europe/Amsterdam
permalink: /posts/:title
plugins:
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-sitemap

feed:
  posts_limit: 20
  excerpt_only: true
  excerpt_tip: "åšæ–‡ç»å¸¸æ›´æ–°ï¼Œè¯·ç§»æ­¥ä¸»ç«™æŸ¥çœ‹ğŸ«¡"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - vercel.json
